sudo: required
dist: xenial
language: cpp
cache: ccache

# regex is for master, release branches, and release tags
branches:
  only:
    - master
    - /^v\d+\.\d+-dev$/
    - /^v(\d+\.){2}\d+$/
    - macos_backwards_compatibility

stages:
  - name: "Stage 1: Dependencies (OpenSSL, Qt)"
  - name: "Stage 2: Dependencies (other)"

env:
  global:
    - CIRP_GITHUB_REPO_SLUG="qTox/qTox-nightly-releases"

jobs:
  include:
    - stage: "Stage 1: Dependencies (OpenSSL, Qt)"
      os: osx
      osx_image: xcode12.2
      env: JOB=build-osx
      cache:
        timeout: 300 # seconds
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup
      script:
        - "./.travis/$JOB.sh 1"
    - stage: "Stage 2: Dependencies (other)"
      os: osx
      osx_image: xcode12.2
      env: JOB=build-osx
      cache:
        timeout: 300 # seconds
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup
      script:
        - "./.travis/$JOB.sh 2"
    - stage: "macOS, AppImage and Flatpak"
      os: osx
      osx_image: xcode12.2
      env: JOB=build-osx
      cache:
        timeout: 300 # seconds
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
      addons:
        homebrew:
          brewfile: ./osx/Brewfile
          update: true
      before_cache:
        - brew cleanup
      script:
        - "./.travis/$JOB.sh"
        - export ARTIFACTS_DIR="$(mktemp -d)"
        - cp -a ./{qTox.dmg,qTox.dmg.sha256} "$ARTIFACTS_DIR"
        - .travis/cirp/cleanup1.sh
        - .travis/cirp/store.sh "$ARTIFACTS_DIR"
        - .travis/cirp/cleanup2.sh


deploy:
  # Linux AppImage
  - provider: releases
    # This is the access token for pushing release builds on Tags
    # Owner: sudden6
    # See https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token
    token:
        secure: "UAvVIUgfH8VGAzMsKk62yz26oqjNpUxEEyZ7OSjt09VoTMuepZd9wPmLCv0b+jFrk5BwQG9gpDzTD7vZ0Un1g1lGD23K801tvMRue/SO/KmOyeYrqd6o7MEFGb22qmmVoid/hqKLQFOxt/5HYj7fnCzG8EUuA9BvdWmsl4ir8Js="
    file_glob: true
    file: ./output/*
    on:
      condition: $JOB == APPIMAGE
      repo: qTox/qTox
      tags: true
    skip_cleanup: true
    draft: true

  # Linux Flatpak
  - provider: releases
    token:
      secure: "UAvVIUgfH8VGAzMsKk62yz26oqjNpUxEEyZ7OSjt09VoTMuepZd9wPmLCv0b+jFrk5BwQG9gpDzTD7vZ0Un1g1lGD23K801tvMRue/SO/KmOyeYrqd6o7MEFGb22qmmVoid/hqKLQFOxt/5HYj7fnCzG8EUuA9BvdWmsl4ir8Js="
    file_glob: true
    file: ./output/*
    on:
      condition: $JOB == FLATPAK
      repo: qTox/qTox
      tags: true
    skip_cleanup: true
    draft: true

  # osx binary
  - provider: releases
    token:
      secure: "UAvVIUgfH8VGAzMsKk62yz26oqjNpUxEEyZ7OSjt09VoTMuepZd9wPmLCv0b+jFrk5BwQG9gpDzTD7vZ0Un1g1lGD23K801tvMRue/SO/KmOyeYrqd6o7MEFGb22qmmVoid/hqKLQFOxt/5HYj7fnCzG8EUuA9BvdWmsl4ir8Js="
    file:
      - "./qTox.dmg"
      - "./qTox.dmg.sha256"
    on:
      condition: $TRAVIS_OS_NAME == osx
      repo: qTox/qTox
      tags: true
    skip_cleanup: true
    draft: true

  # Windows Installer 64Bit
  - provider: releases
    token:
      secure: "UAvVIUgfH8VGAzMsKk62yz26oqjNpUxEEyZ7OSjt09VoTMuepZd9wPmLCv0b+jFrk5BwQG9gpDzTD7vZ0Un1g1lGD23K801tvMRue/SO/KmOyeYrqd6o7MEFGb22qmmVoid/hqKLQFOxt/5HYj7fnCzG8EUuA9BvdWmsl4ir8Js="
    file:
      - "./workspace/x86_64/qtox/release/setup-qtox-x86_64-release.exe"
      - "./workspace/x86_64/qtox/release/setup-qtox-x86_64-release.exe.sha256"
    on:
      condition: $WINDOWS_BUILD_ARCH_CACHE_TRICK_VARIABLE == x86_64 && -f /home/travis/build/qTox/qTox/stage3 && -f /home/travis/build/qTox/qTox/release
      repo: qTox/qTox
      tags: true
    skip_cleanup: true
    draft: true

  # Windows Installer 32Bit
  - provider: releases
    token:
      secure: "UAvVIUgfH8VGAzMsKk62yz26oqjNpUxEEyZ7OSjt09VoTMuepZd9wPmLCv0b+jFrk5BwQG9gpDzTD7vZ0Un1g1lGD23K801tvMRue/SO/KmOyeYrqd6o7MEFGb22qmmVoid/hqKLQFOxt/5HYj7fnCzG8EUuA9BvdWmsl4ir8Js="
    file:
      - "./workspace/i686/qtox/release/setup-qtox-i686-release.exe"
      - "./workspace/i686/qtox/release/setup-qtox-i686-release.exe.sha256"
    on:
      condition: $WINDOWS_BUILD_ARCH_CACHE_TRICK_VARIABLE == i686 && -f /home/travis/build/qTox/qTox/stage3 && -f /home/travis/build/qTox/qTox/release
      repo: qTox/qTox
      tags: true
    skip_cleanup: true
    draft: true

after_success:
  - >
    test "$TRAVIS_PULL_REQUEST" == "false"
    && test "$TRAVIS_BRANCH" == "master"
    && test "$JOB" == "build-docs"
    && bash ./.travis/deploy-docs.sh
  - >
    test "$TRAVIS_PULL_REQUEST" == "false"
    && test "$TRAVIS_BRANCH" == "master"
    && test "$JOB" == "build-gitstats"
    && bash ./.travis/deploy-gitstats.sh
